@echo off
SETLOCAL ENABLEDELAYEDEXPANSION

:: Default values
SET ORACLE_SID=ORCL
SET DIRECTORY=DATA_PUMP_DIR
SET SCHEMA=SCOTT
SET TABLES=
SET PARALLEL=4
SET COMPRESSION=ALL
SET FILESIZE=10G
SET EXPORT_VERSION=LATEST

:: User input
set /p ORACLE_SID="Enter ORACLE_SID (default: %ORACLE_SID%): " 
IF NOT DEFINED ORACLE_SID SET ORACLE_SID=ORCL

set /p DIRECTORY="Enter Directory Object (default: %DIRECTORY%): " 
IF NOT DEFINED DIRECTORY SET DIRECTORY=DATA_PUMP_DIR

set /p SCHEMA="Enter Schema Name (default: %SCHEMA%): " 
IF NOT DEFINED SCHEMA SET SCHEMA=SCOTT

set /p TABLES="Enter Table(s) to Export (comma-separated or leave blank for full schema): " 
IF NOT DEFINED TABLES (
    SET MODE=SCHEMA
    SET FILE_SUFFIX=ALL
) ELSE (
    SET MODE=TABLE
    SET FILE_SUFFIX=!TABLES!
    SET FILE_SUFFIX=!FILE_SUFFIX:,=_!
)

set /p FILESIZE="Enter Dump File Size Limit (e.g., 5G, 10G) (default: %FILESIZE%): "
IF NOT DEFINED FILESIZE SET FILESIZE=10G

set /p PARALLEL="Enter Parallel Workers (default: %PARALLEL%): " 
IF NOT DEFINED PARALLEL SET PARALLEL=4

set /p EXPORT_VERSION="Enter Export Version (e.g., 11.2, 12.1, 19c) (default: %EXPORT_VERSION%): "
IF NOT DEFINED EXPORT_VERSION SET EXPORT_VERSION=LATEST

:: Generate timestamp
FOR /F "tokens=2 delims==" %%I IN ('wmic OS Get localdatetime /value') DO SET DATETIME=%%I
SET DATETIME=%DATETIME:~0,8%_%DATETIME:~8,6%

:: Generate dump and log file names with "EXPDP_" prefix
SET DUMPFILE=EXPDP_%SCHEMA%_%FILE_SUFFIX%_%DATETIME%.dmp
SET LOGFILE=EXPDP_%SCHEMA%_%FILE_SUFFIX%_%DATETIME%.log

:: Running Data Pump Export
echo Running Data Pump Export...
IF "%MODE%"=="SCHEMA" (
    expdp system/password@%ORACLE_SID% SCHEMAS=%SCHEMA% DIRECTORY=%DIRECTORY% DUMPFILE=%DUMPFILE% LOGFILE=%LOGFILE% FILESIZE=%FILESIZE% PARALLEL=%PARALLEL% COMPRESSION=%COMPRESSION% VERSION=%EXPORT_VERSION%
) ELSE (
    expdp system/password@%ORACLE_SID% TABLES=%TABLES% DIRECTORY=%DIRECTORY% DUMPFILE=%DUMPFILE% LOGFILE=%LOGFILE% FILESIZE=%FILESIZE% PARALLEL=%PARALLEL% COMPRESSION=%COMPRESSION% VERSION=%EXPORT_VERSION%
)

echo Export Completed!
PAUSE