CREATE TABLE TEMP_MOBILE_UPLOAD (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MOBILE_NO VARCHAR2(15)
);


DECLARE
    l_blob        BLOB;
    l_clob        CLOB;
    l_line        VARCHAR2(4000);
    l_pos         PLS_INTEGER := 1;
    l_total_lines PLS_INTEGER;
BEGIN
    -- Clear old data
    DELETE FROM TEMP_MOBILE_UPLOAD;

    -- Get file contents
    SELECT blob_content INTO l_blob
    FROM apex_application_temp_files
    WHERE name = :P1_FILE_UPLOAD;

    -- Convert BLOB to CLOB
    l_clob := apex_web_service.blob2clobbase64(l_blob);
    l_clob := utl_raw.cast_to_varchar2(utl_encode.base64_decode(utl_raw.cast_to_raw(l_clob)));

    -- Parse each line
    LOOP
        l_line := REGEXP_SUBSTR(l_clob, '[^' || CHR(10) || ']+', 1, l_pos);
        EXIT WHEN l_line IS NULL;

        -- Insert line as mobile number
        INSERT INTO TEMP_MOBILE_UPLOAD (MOBILE_NO)
        VALUES (TRIM(l_line));

        l_pos := l_pos + 1;
    END LOOP;

    COMMIT;
END;

-- Insert cleaned mobile number
INSERT INTO TEMP_MOBILE_UPLOAD (MOBILE_NO)
VALUES (
  TRIM(REPLACE(REPLACE(l_line, CHR(13), ''), CHR(10), ''))
);